services:
  - type: web
    name: donation-system
    env: python
    plan: free
    rootDir: donation
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn donation.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: RENDER
        value: "True"

databases:
  - name: donation-db
    databaseName: donation_db
    user: donation_user
    plan: free
