[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "python manage.py runserver 0.0.0.0:$PORT"

[variables]
DJANGO_SETTINGS_MODULE = "donation.settings"
DEBUG = "True"
