[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python manage.py runserver 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
DJANGO_SETTINGS_MODULE = "donation.settings"
DEBUG = "True"
ALLOWED_HOSTS = "*"
