services:
  - type: web
    name: django-donation-app
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn donation.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: donation.settings_production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"

databases:
  - name: django-donation-db
    plan: free
