services:
  - type: web
    name: donation-system
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn donation.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SITE_DOMAIN
        value: "donation-system.onrender.com"
      - key: SITE_NAME
        value: "Donation System"

databases:
  - name: donation-db
    databaseName: donation_db
    user: donation_user
