services:
  - type: web
    name: django-donation-app
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      export DJANGO_SETTINGS_MODULE=donation.settings_production
      python manage.py collectstatic --noinput
    startCommand: python -m gunicorn donation.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: donation.settings_production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: django-donation-db
    plan: free
